export enum DETAIL_TYPES {
  NOTIFICATIONS = "notifications/action",
  SMS_REPLIES = "notifications/reply",
  CHAT_ACTIONS = "chats/action",
  APPOINTMENT_CREATED = "appointment/created",
  APPOINTMENT_CANCELED = "appointment/canceled",
  STRIPE_EVENTS = "payments/stripe-events",
  UPDATE_INTERNAL_CREDIT = "payments/update-internal-credit",
  CREATE_STRIPE_CUSTOMER = "payments/create-stripe-customer",
  MARKETING_UPDATES = "marketing/updates",
  MARKETING_SET_STATUS_TAG = "marketing/set-tag",
  MARKETING_FACEBOOK_EVENT = "marketing/facebook-event",
  REWARD_REFERRALS = "referral/reward",
  CREATE_REFERRAL_USER = "referral/create-user",
}
