export const generateParentFieldsBirthDefects = () => [
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 384,
    y: 689,
    width: 120,
    height: 12,
    required: true,
    name: "Date_2",
    label: "Date",
    lock_to_sign_date: false,
    color: "000000",
    bold: false,
    italic: false,
    underline: false,
    align: "left",
    font: "Arial",
    max_lines: 1,
    max_chars: 10,
    validator_id: "13435fa6c2a17f83177fcbb5c4a9376ce85befeb",
    arrangement: "none",
    size: 14.545454545454547,
    valign: "top",
    type: "text",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 171,
    y: 687,
    width: 185,
    height: 11,
    required: true,
    name: "Signature_3",
    allowed_types: ["type", "draw", "upload"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 631,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_27",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 106,
    y: 623,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_26",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 106,
    y: 584,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_25",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 102,
    y: 444,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_18",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 406,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_24",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 102,
    y: 371,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_17",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 329,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_23",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 102,
    y: 313,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_16",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 291,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_22",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 102,
    y: 272,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_15",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 237,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_21",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 388,
    y: 126,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_20",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
  {
    page_number: 0,
    role: "Parent/Guardian",
    x: 391,
    y: 96,
    width: 36,
    height: 12,
    required: true,
    name: "Initials_19",
    allowed_types: ["type", "draw"],
    type: "signature",
  },
];
